version: '3.3'

services:
  flask-app1:
    image: flask-init
    environment:
      DEBUG_MODE: 'True'
    volumes:
      - "./flask-init:/flask-init"
    ports:
      - "80:8080"
  flask-app2:
    image: flask-init
    environment:
      DEBUG_MODE: 'True'
    volumes:
      - "./flask-init:/flask-init"
    ports:
      - "81:8080"
